# Generated by Django 3.2.9 on 2021-11-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211115_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommendation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Описание появится позже'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.TextField(default='Характеристики появятся позже'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Описание появится позже'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
